version: '3'
services:
  BIRD3:
    build: .
    image: bird3
    ports:
      - '127.0.0.1:4878:4878'
    volumes:
      - './:/srv/bird3/'
    links:
      - 'PostgreSQL:db'
      - 'Redis:redis'
      - 'axibase_astd:astd'
    depends_on:
      - PostgreSQL
      - Redis
      - axibase_astd
  PostgreSQL:
    image: 'sameersbn/postgresql:10'
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - DEBUG=false
      - DB_USER=pgdocker
      - DB_PASS=pgdocker
      - 'DB_NAME=${APP_NAME}'
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    volumes:
      - './data/postgres:/var/lib/postgresql'
  Redis:
    image: 'redis:latest'
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - './data/redis:/data'
  axibase_astd:
    image: 'axibase/atsd:latest'
    restart: always
    environment:
      - ADMIN_USER_NAME=
      - ADMIN_USER_PASSWORD=
      - COLLECTOR_USER_NAME=
      - COLLECTOR_USER_PASSWORD=
      - COLLECTOR_USER_TYPE=
      - DB_TIMEZONE=
      - JAVA_OPTS=
      - HADOOP_OPTS=
      - HBASE_OPTS=
    volumes:
      - './data/atsd:/opt/atsd'
